name: wuudz
description: Flutter component package
version: 0.0.1
homepage: declan.sh

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  jiffy: ^4.1.0
  flutter_bloc: ^8.0.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  flutter_markdown: ^0.6.8
  visibility_detector: ^0.2.2
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  monarch: ^2.1.0
  build_runner: ^2.1.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
